# Exploración Base de Datasets Procesados de MiBici (v1.1)

Este notebook realiza la carga y exploración inicial de los datos consolidados en formato Parquet:
- **Nomenclatura (estaciones)** desde `data/processed/estaciones.parquet`
- **Viajes completos** desde las particiones de `data/processed/viajes/`

Se utilizan las funciones modulares de `mi_bici.dataset`.

In [ ]:
from mi_bici.dataset import load_processed_stations, load_processed_travels

2026-10-17 21:41:40.599 | INFO     | mi_bici.config:<module>:12 - PROJ_ROOT path is: /home/miguel/Maestria/Trimestre4/mlops/TC5061-Proyecto-Equipo03

## 1. Nomenclatura de Estaciones

In [ ]:
df_estaciones = load_processed_stations()
df_estaciones.info()

<class 'pandas.DataFrame'>
RangeIndex: 484 entries, 0 to 483
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          484 non-null    int64
 1   name        484 non-null    str
 2   latitude    484 non-null    float64
 3   longitude   484 non-null    float64
 4   dpcapacity  484 non-null    int64
dtypes: float64(2), int64(2), str(1)
memory usage: 38.9 KB

In [3]:
df_estaciones.head(10)

,id,name,latitude,longitude,dpcapacity
0,2,(GDL-001) C. Epigmenio Glez./ Av. 16 de Sept.,20.666378,-103.348820,15
1,3,(GDL-002) C. Colonias / Av. Niños héroes,20.667228,-103.366000,15
2,4,(GDL-003) C. Vidrio / Av. Chapultepec,20.667690,-103.368252,19
3,5,(GDL-004) C. Ghilardi /C. Miraflores,20.691847,-103.362549,19
4,6,(GDL-005) C. San Diego /Calzada Independencia,20.681158,-103.339363,11
5,8,(GDL-006) C. Venustiano Carranza /C. Reforma,20.680717,-103.344415,11
6,9,(GDL-007) C. Epigmenio Glez./Av. Cristobal C.,20.666771,-103.350562,15
7,10,(GDL-008) C. Ignacio Zaragoza / C. J. Angulo,20.681953,-103.349992,15
8,11,(GDL-009) Calz. Federalismo/ C. J. Angulo,20.682077,-103.353835,23
9,12,(GDL-010) C. Cruz verde / C. Joaquin Angulo,20.681852,-103.357338,15

## 2. Viajes Completos

In [4]:
df_viajes = load_processed_travels()
df_viajes.info()

<class 'pandas.DataFrame'>
RangeIndex: 9074565 entries, 0 to 9074564
Data columns (total 9 columns):
 #   Column        Dtype
---  ------        -----
 0   genero        str
 1   nacimiento    int64
 2   inicio        str
 3   fin           str
 4   origen        int64
 5   destino       int64
 6   duracion_min  Int64
 7   anio          category
 8   mes           category
dtypes: Int64(1), category(2), int64(3), str(3)
memory usage: 796.2 MB

In [5]:
df_viajes.head(10)

,genero,nacimiento,inicio,fin,origen,destino,duracion_min,anio,mes
0,M,1979,2025-10-01 00:00,2025-10-01 00:08,244,46,8,2025,10
1,M,1976,2025-10-01 00:00,2025-10-01 00:07,31,6,7,2025,10
2,M,1992,2025-10-01 00:00,2025-10-01 00:07,73,39,6,2025,10
3,M,1996,2025-10-01 00:00,2025-10-01 00:13,21,248,12,2025,10
4,M,1990,2025-10-01 00:02,2025-10-01 00:29,81,35,26,2025,10
5,M,1995,2025-10-01 00:02,2025-10-01 00:08,16,16,5,2025,10
6,M,1991,2025-10-01 00:03,2025-10-01 00:10,333,163,7,2025,10
7,M,1998,2025-10-01 00:03,2025-10-01 00:10,333,163,7,2025,10
8,M,1982,2025-10-01 00:03,2025-10-01 00:16,280,173,13,2025,10
9,M,2001,2025-10-01 00:03,2025-10-01 00:16,168,155,13,2025,10

In [5]:
df_viajes.isna().sum()

genero          0
nacimiento      0
inicio          0
fin             0
origen          0
destino         0
duracion_min    0
anio            0
mes             0
dtype: int64